export const LOGIN = '/login'
export const DASHBOARD = '/dashboard'
export const HOME = '/'
export const DARK = 'dark'
export const LIGHT = 'light'
export const BASIC_INFORMATION_TYPE = 'basic_information'
export const EDUCATION_TYPE = 'education'
export const SOCIAL_LINKS_TYPE = 'social_links'
